services:
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports: ["27017:27017"]
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - backend-network

  api:
    build:
      context: ./services/api-nestjs
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/desafio_gdash
    env_file:
      - ./services/api-nestjs/.env
    ports: ["3000:3000"]
    depends_on: ["mongo","rabbitmq"]
    networks:
      - backend-network
      - frontend-network

  python-collector:
    build:
      context: ./services/python-service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
    depends_on: ["rabbitmq"]
    networks:
      - backend-network

  go-worker:
    build:
      context: ./services/go-worker
      dockerfile: Dockerfile
    depends_on: ["rabbitmq","api"]
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: ["5173:80"]
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on: ["api"]
    networks:
      - backend-network
      - frontend-network

volumes:
  mongo-data:
    driver: local

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge