weather:
  api_url: "" # ex: https://api.openweathermap.org/data/2.5/weather
  api_key: "" # sua chave de API
  city: "SÃ£o Paulo"

rabbitmq:
  url: "amqp://rabbitmq:5672/"
  queue: "weather"

worker:
  interval_seconds: 3600
