services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - climate-sync

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=climate-sync
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - climate-sync

  nestjs-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/climate-sync
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - climate-sync

  python-producer:
    build:
      context: ./python_producer
    container_name: climate-sync-python-producer
    env_file:
      - ./.env
    environment:
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - COLLECTION_INTERVAL_MINUTES=${COLLECTION_INTERVAL_MINUTES}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - climate-sync

  go-worker:
    build:
      context: ./go-worker
    container_name: climate-sync-go-worker
    env_file:
      - ./.env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - climate-sync

volumes:
  mongo_data:

networks:
  climate-sync:
    driver: bridge
